---
- name: warn that memcached should be restarted
  ansible.builtin.debug:
    msg:
      - "****"
      - "**** !!! MANUAL RESTART NEEDED !!!"
      - "**** Configuration files changed! "
      - "**** You have to restart memcached manually"
      - "****"
  when: not memcached_restart

- name: systemctl restart memcached@{{ memcached_port }}.service
  ansible.builtin.service:
    name: memcached@{{ memcached_port }}.service
    state: restarted
  when: memcached_restart
