---
- name: Converge
  hosts: all
  tasks:
    - name: role with default option
      ansible.builtin.include_role:
        name: claranet.memcached

    - name: role no default port
      ansible.builtin.include_role:
        name: claranet.memcached
      vars:
        memcached_port: 11212
        memcached_restart: true
        memcached_extra_options:
          - t 8
